version: '2'
services:

  webscholar:
    build:
      context: ./webscholar-web
      dockerfile: ./Dockerfile
    ports:
      - "80:8080"
      - "370:3700"
    depends_on:
      - webscholar-postgres
    volumes:
      - ./logs:/usr/glassfish4/glassfish/domains/domain1/logs

  webscholar-postgres:
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    ports:
      - "2345:5432" # Bind host port 5432 to PostgreSQL port 5432

  #core:
  #  build:
  #    context: ./core
  #    dockerfile: ./Dockerfile
  #  volumes:
  #    - ./core/logs:/usr/glassfish4/glassfish/domains/domain1/logs
  #  ports:
  #    - "370:3700"